name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: rustup update stable
    - name: Rust Cache
      uses: Swatinem/rust-cache@v1.3.0
    - name: Format
      run: cargo fmt --all -- --check
    - name: Run clippy
      run: cargo clippy --all-targets --all-features --verbose -- -D warnings
    - name: Build
      run: cargo build --all-targets --all-features --verbose
    - name: Run tests
      run: cargo test --verbose
